### ISSUE TITLE
[Feature] Add - 회원가입

### ISSUE THREAD

**Issue by sim0417** [codestates/the-GOD-server#10]
### ISSUE
- Group:  `server`
- Type: `Add`
- Detail: 회원가입 기능을 작성합니다

### TODO
1. [x] 데이터 유효성 확인
2. [x] 각 응답코드에 대한 처리 작성
3. [x] 데이터베이스에 데이터가 정상적으로 업로드 되는지 확인
