### ISSUE TITLE
[Feature] Add - 루트 작성

### ISSUE THREAD

**Issue by yoontaek0928** [codestates/the-GOD-server#18]
### ISSUE
- Group:  `server`
- Type: `Add`
- Detail: 유저가 원하는 루트를 작성합니다

### TODO
1. [ ] 유저가 루트를 작성하고자 할 때, 순서대로 루트가 잘 작성되는 지 확인
2. [ ] 테스트 코드 작성
3. [ ] 데이터 유효성 검사
