### ISSUE TITLE
[Feature] Add  - 컨텐츠 생성

### ISSUE THREAD

**Issue by yoontaek0928** [codestates/the-GOD-server#2]
### ISSUE
- Group:  `server`
- Type: `Add`
- Detail: 클라이언트에서 받아온 정보를 컨텐츠 다큐먼트에 저장하는 작업입니다.

### TODO
1. [ ] DB에 정보가 저장되는 지 확인
2. [ ] 테스트 코드 작성
3. [ ] 데이터 유효성 검사
