### ISSUE TITLE
[Feature] Add - User 아티스트 팔로우

### ISSUE THREAD

**Issue by sim0417** [codestates/the-GOD-server#23]
### ISSUE
- Group:  `server`
- Type: `Add`
- Detail: 사용자가 아티스트 팔로우를 추가하거나 취소 할수 있는 기능 작성

### TODO
1. [ ] 상태 코드에 따른 동작 작성
2. [ ] 데이터 베이스에 변경한 데이터가 업로드 되는지 확인
3. [ ] 테스트 코드 작성
