### ISSUE TITLE
[Feature] Add - 데이터 베이스 연결

### ISSUE THREAD

**Issue by sim0417** [codestates/the-GOD-server#3]
### ISSUE
- Group:  `client`
- Type: `Add`
- Detail: MongoDB 데이터 베이스를 서버와 연동합니다.

### TODO
1. [ ] mongoose 를 사용해서 데이터 베이스에 연결
2. [ ] 데이터 베이스 테스트 - 데이터 CRUD 확인 
3. [ ] 데이터 베이스에 필요한 설정을 완료한다
4. [ ] Collection 작성
5. [ ] Document 작성
