### ISSUE TITLE
[Feature] Add - User name update

### ISSUE THREAD

**Issue by sim0417** [codestates/the-GOD-server#52]
### ISSUE
- Group:  `server`
- Type: `Add`
- Detail: 사용자의 이름을 변경합니다.

### TODO
1. [x] 상태코드에 따른 동작 작성
2. [x] 데이터베이스에 데이터가 업로드 되는지 확인
3. [ ] 테스트 코드 작성
