### ISSUE TITLE
[Feature] Refactor - 토큰 & 미들웨어 관련 리팩토링입니다

### ISSUE THREAD

**Issue by yoontaek0928** [codestates/the-GOD-server#84]
### ISSUE
- Group:  `server`
- Type:  `Refactor`
- Detail: 코드 개선을 위한 리팩토링 작업입니다

### TODO
1. [ ] 토큰 발급 및 확인 파라미터 변경 ( 이메일 -> 아이디 )
2. [ ] API 추가(회원탈퇴, 리프레시 토큰 이용하여 액세스 토큰 발급)
3. [ ] 회원가입 시 중복 체크
